# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0002_gameresult_gameresultmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='GameResultMember',
            new_name='Game_Result_Member',
        ),
        migrations.DeleteModel(
            name='GameResult',
        ),
    ]
