# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0003_auto_20170514_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_result_member',
            old_name='game_result_pk',
            new_name='game_result_id',
        ),
        migrations.RenameField(
            model_name='game_result_member',
            old_name='user_pk',
            new_name='user_id',
        ),
    ]
