# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0004_auto_20170514_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_Result_Member',
            new_name='Game_Result_Users',
        ),
        migrations.RenameModel(
            old_name='Game_Result',
            new_name='Game_Results',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
